name: Push Master to GHPages

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master   
        
    - name: GitHub Push
      uses: ad-m/github-push-action@master
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.OTHER_TOKEN }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: EndlessHosting/endlesshosting.github.io
        # Destination branch to push changes
        branch: master
        # Determines if force push is used
        force: true
        # Directory to change to before pushing.
