name: Push Master to GHPages

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Commit files
      run: |
        git config --local user.email "support@theendlessweb.com"
        git config --local user.name "EH Robot"
        git commit -m "Publish changes from EndlessHosting/website" -a
    - name: GitHub Push
      uses: ad-m/github-push-action@master
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.OTHER_TOKEN }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: https://github.com/EndlessHosting/endlesshosting.github.io.git
        # Destination branch to push changes
        branch: master
        # Determines if force push is used
        force: true
        # Directory to change to before pushing.
